package com.clivern.racter;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.testng.annotations.*;
import static org.testng.Assert.*;

public class BotPlatformTest {
    @Test public void someLibraryMethodReturnsTrue() {
        BotPlatform classUnderTest = new BotPlatform();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}